[project]
name = "10"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=5.2.8",
    "fastapi>=0.122.0",
    "httpx>=0.28.1",
    "pytest>=9.0.1",
    "uvicorn>=0.38.0",
]
